name: Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  id-token: write # required for requesting the JWT
  contents: read  # required for actions/checkout

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: us-west-2

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions
          role-duration-seconds: 900

      - name: Install
        run: python -m pip install --upgrade pip build twine

      - name: Build
        run: |
          echo ${{ github.ref_name }} | echo __version__=\"$(sed 's/v//')\" > ./eventsourcing/__init__.py
          python -m build --sdist --wheel

      - name: Publish
        run: |
          aws codeartifact login --tool twine --repository pypi-internal --domain hardloop --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --region ${{ env.AWS_REGION }}
          twine upload --verbose --repository codeartifact dist/*
